/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type HolidayData struct {
	Date *Object `json:"date,omitempty"`
	Description *Object `json:"description,omitempty"`
	HolidayType *Object `json:"holiday_type,omitempty"`
	ClosedExchanges *Object `json:"closed_exchanges,omitempty"`
	OpenExchanges *Object `json:"open_exchanges,omitempty"`
}
