/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProfileData struct {
	// E-mail address of the user
	Email *Object `json:"email,omitempty"`
	// Lists the exchanges to which the user has access
	Exchanges *Object `json:"exchanges,omitempty"`
	// Lists the products types to which the user has access
	Products *Object `json:"products,omitempty"`
	// The broker ID
	Broker *Object `json:"broker,omitempty"`
	// Uniquely identifies the user
	UserId *Object `json:"user_id,omitempty"`
	// Name of the user
	UserName *Object `json:"user_name,omitempty"`
	// Order types enabled for the user
	OrderTypes *Object `json:"order_types,omitempty"`
	//   Identifies the user's registered role at the broker. This will be individual for all retail users
	UserType *Object `json:"user_type,omitempty"`
	//   To depict if the user has given power of attorney for transactions
	Poa *Object `json:"poa,omitempty"`
	//   Indicates if DDPI is enabled for trading
	Ddpi *Object `json:"ddpi,omitempty"`
	//   Whether the status of account is active or not
	IsActive *Object `json:"is_active,omitempty"`
}
