/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MarketData struct {
	Ltp *Object `json:"ltp,omitempty"`
	Volume *Object `json:"volume,omitempty"`
	Oi *Object `json:"oi,omitempty"`
	ClosePrice *Object `json:"close_price,omitempty"`
	BidPrice *Object `json:"bid_price,omitempty"`
	BidQty *Object `json:"bid_qty,omitempty"`
	AskPrice *Object `json:"ask_price,omitempty"`
	AskQty *Object `json:"ask_qty,omitempty"`
	PrevOi *Object `json:"prev_oi,omitempty"`
}
