/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TradeHistoryResponseTradeData struct {
	Exchange *Object `json:"exchange,omitempty"`
	Segment *Object `json:"segment,omitempty"`
	OptionType *Object `json:"option_type,omitempty"`
	Quantity *Object `json:"quantity,omitempty"`
	Amount *Object `json:"amount,omitempty"`
	TradeId *Object `json:"trade_id,omitempty"`
	TradeDate *Object `json:"trade_date,omitempty"`
	TransactionType *Object `json:"transaction_type,omitempty"`
	ScripName *Object `json:"scrip_name,omitempty"`
	StrikePrice *Object `json:"strike_price,omitempty"`
	Expiry *Object `json:"expiry,omitempty"`
	Price *Object `json:"price,omitempty"`
	Isin *Object `json:"isin,omitempty"`
	Symbol *Object `json:"symbol,omitempty"`
	InstrumentToken *Object `json:"instrument_token,omitempty"`
}
