/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ModifyOrderRequest struct {
	// Quantity with which the order was placed
	Quantity *Object `json:"quantity,omitempty"`
	// Order validity (DAY- Day and IOC- Immediate or Cancel (IOC) order)
	Validity *Object `json:"validity"`
	// Price at which the order was placed
	Price *Object `json:"price"`
	// The order ID for which the order must be modified
	OrderId *Object `json:"order_id"`
	// Type of order. It can be one of the following MARKET refers to market order LIMILT refers to Limit Order SL refers to Stop Loss Limit SL-M refers to Stop Loss Market
	OrderType *Object `json:"order_type"`
	// The quantity that should be disclosed in the market depth
	DisclosedQuantity *Object `json:"disclosed_quantity,omitempty"`
	// If the order is a stop loss order then the trigger price to be set is mentioned here
	TriggerPrice *Object `json:"trigger_price"`
}
