/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MarketQuoteOptionGreekV3 struct {
	LastPrice *Object `json:"last_price,omitempty"`
	InstrumentToken *Object `json:"instrument_token,omitempty"`
	Ltq *Object `json:"ltq,omitempty"`
	Volume *Object `json:"volume,omitempty"`
	Cp *Object `json:"cp,omitempty"`
	Iv *Object `json:"iv,omitempty"`
	Vega *Object `json:"vega,omitempty"`
	Gamma *Object `json:"gamma,omitempty"`
	Theta *Object `json:"theta,omitempty"`
	Delta *Object `json:"delta,omitempty"`
	Oi *Object `json:"oi,omitempty"`
}
