/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Rule struct {
	Strategy *Object `json:"strategy,omitempty"`
	Status *Object `json:"status,omitempty"`
	Message *Object `json:"message,omitempty"`
	TriggerType *Object `json:"trigger_type,omitempty"`
	TriggerPrice *Object `json:"trigger_price,omitempty"`
	TransactionType *Object `json:"transaction_type,omitempty"`
	OrderId *Object `json:"order_id,omitempty"`
	TrailingGap *Object `json:"trailing_gap,omitempty"`
}
