/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MultiOrderData struct {
	// A unique identifier for tracking individual orders within the batch
	CorrelationId *Object `json:"correlation_id,omitempty"`
	// An order ID for the order request placed
	OrderId *Object `json:"order_id,omitempty"`
}
