/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LogoutResponse struct {
	Status *Object `json:"status,omitempty"`
	// Logout status
	Data *Object `json:"data,omitempty"`
}
