/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserFundMarginData struct {
	// Positive values denote the amount blocked into an Open order or position.  Negative value denotes the amount being released.
	UsedMargin *Object `json:"used_margin,omitempty"`
	// Instant payin will reflect here
	PayinAmount *Object `json:"payin_amount,omitempty"`
	// Amount blocked on futures and options towards SPAN
	SpanMargin *Object `json:"span_margin,omitempty"`
	// Payin amount credited through a manual process
	AdhocMargin *Object `json:"adhoc_margin,omitempty"`
	// The amount maintained for withdrawal
	NotionalCash *Object `json:"notional_cash,omitempty"`
	// Total margin available for trading
	AvailableMargin *Object `json:"available_margin,omitempty"`
	// Amount blocked on futures and options towards Exposure
	ExposureMargin *Object `json:"exposure_margin,omitempty"`
}
