/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ConvertPositionRequest struct {
	// Key of the instrument
	InstrumentToken *Object `json:"instrument_token"`
	// Indicates the new product to use for the convert positions
	NewProduct *Object `json:"new_product"`
	// Indicates the old product to use for the convert positions
	OldProduct *Object `json:"old_product"`
	// Indicates whether its a buy(b) or sell(s) order
	TransactionType *Object `json:"transaction_type"`
	// Quantity with which the position to convert
	Quantity *Object `json:"quantity"`
}
