/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MarketQuoteSymbolLtpV3 struct {
	LastPrice *Object `json:"last_price,omitempty"`
	InstrumentToken *Object `json:"instrument_token,omitempty"`
	Ltq *Object `json:"ltq,omitempty"`
	Volume *Object `json:"volume,omitempty"`
	Cp *Object `json:"cp,omitempty"`
}
