/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OtherTaxes struct {
	// Transaction charges
	Transaction *Object `json:"transaction,omitempty"`
	// Clearing charges
	Clearing *Object `json:"clearing,omitempty"`
	// IPF charges
	Ipft *Object `json:"ipft,omitempty"`
	// SEBI turnover charges
	SebiTurnover *Object `json:"sebi_turnover,omitempty"`
}
