/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PlaceOrderResponse struct {
	Status *Object `json:"status,omitempty"`
	// Response data for place order request
	Data *PlaceOrderData `json:"data,omitempty"`
}
