/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OrderData struct {
	// Exchange to which the order is associated
	Exchange *Object `json:"exchange,omitempty"`
	// Price at which the order was placed
	Price *Object `json:"price,omitempty"`
	// Shows if the order was either Intraday, Delivery, CoverOrder or OneCancelsOther
	Product *Object `json:"product,omitempty"`
	// Quantity with which the order was placed
	Quantity *Object `json:"quantity,omitempty"`
	// Indicates the current status of the order. Valid order status’ are outlined in the table below
	Status *Object `json:"status,omitempty"`
	// Tag to uniquely identify an order
	Tag *Object `json:"tag,omitempty"`
	// Order validity (DAY- Day and IOC- Immediate or Cancel (IOC) order)
	Validity *Object `json:"validity,omitempty"`
	// Average price at which the qty got traded
	AveragePrice *Object `json:"average_price,omitempty"`
	// The quantity that should be disclosed in the market depth
	DisclosedQuantity *Object `json:"disclosed_quantity,omitempty"`
	// Unique order ID assigned by the exchange for the order placed
	ExchangeOrderId *Object `json:"exchange_order_id,omitempty"`
	// User readable time at which the order was placed or updated
	ExchangeTimestamp *Object `json:"exchange_timestamp,omitempty"`
	// Identifier issued by Upstox used for subscribing to live market quotes
	InstrumentToken *Object `json:"instrument_token,omitempty"`
	// Signifies if the order is an After Market Order
	IsAmo *Object `json:"is_amo,omitempty"`
	// Indicates the reason when any order is rejected, not modified or cancelled
	StatusMessage *Object `json:"status_message,omitempty"`
	// Unique order ID assigned internally for the order placed
	OrderId *Object `json:"order_id,omitempty"`
	// Apart from 1st order it shows the count of how many requests were sent
	OrderRequestId *Object `json:"order_request_id,omitempty"`
	// Type of order. It can be one of the following MARKET refers to market order<br>LIMIT refers to Limit Order<br>SL refers to Stop Loss Limit<br>SL-M refers to Stop loss market
	OrderType *Object `json:"order_type,omitempty"`
	// In case the order is part of the second or third leg of a CO or OCO, the parent order ID is indicated here
	ParentOrderId *Object `json:"parent_order_id,omitempty"`
	// Shows the trading symbol of the instrument
	Tradingsymbol *Object `json:"tradingsymbol,omitempty"`
	// Shows the trading symbol of the instrument
	TradingSymbol *Object `json:"trading_symbol,omitempty"`
	// User readable timestamp at which the order was placed
	OrderTimestamp *Object `json:"order_timestamp,omitempty"`
	// The total quantity traded from this particular order
	FilledQuantity *Object `json:"filled_quantity,omitempty"`
	// Indicates whether the order was a buy or sell order
	TransactionType *Object `json:"transaction_type,omitempty"`
	// If the order was a stop loss order then the trigger price set is mentioned here
	TriggerPrice *Object `json:"trigger_price,omitempty"`
	// Uniquely identifies the user
	PlacedBy *Object `json:"placed_by,omitempty"`
	// Order complexity
	Variety *Object `json:"variety,omitempty"`
}
