/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Depth struct {
	// quantity
	Quantity *Object `json:"quantity,omitempty"`
	// price
	Price *Object `json:"price,omitempty"`
	// orders
	Orders *Object `json:"orders,omitempty"`
}
