/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GttOrderDetails struct {
	Type_ *Object `json:"type,omitempty"`
	Exchange *Object `json:"exchange,omitempty"`
	Quantity *Object `json:"quantity,omitempty"`
	Product *Object `json:"product,omitempty"`
	Rules *Object `json:"rules,omitempty"`
	TradingSymbol *Object `json:"trading_symbol,omitempty"`
	InstrumentToken *Object `json:"instrument_token,omitempty"`
	GttOrderId *Object `json:"gtt_order_id,omitempty"`
	ExpiresAt *Object `json:"expires_at,omitempty"`
	CreatedAt *Object `json:"created_at,omitempty"`
}
