/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TradeHistoryResponse struct {
	Status *Object `json:"status,omitempty"`
	Data *Object `json:"data,omitempty"`
	MetaData *TradeHistoryResponseMetaData `json:"metaData,omitempty"`
}
