/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OhlcV3 struct {
	// The open price of the trading session
	Open *Object `json:"open,omitempty"`
	// The high price of the trading session
	High *Object `json:"high,omitempty"`
	// The low price of the trading session
	Low *Object `json:"low,omitempty"`
	// The close price of the symbol from the previous session of trading
	Close *Object `json:"close,omitempty"`
	// The volume of the symbol traded in the session
	Volume *Object `json:"volume,omitempty"`
	// Starting timestamp of candle
	Ts *Object `json:"ts,omitempty"`
}
