/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MarketStatusData struct {
	Exchange *Object `json:"exchange,omitempty"`
	Status *Object `json:"status,omitempty"`
	LastUpdated *Object `json:"last_updated,omitempty"`
}
