/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MarketQuoteOhlcv3 struct {
	// The last traded price of symbol
	LastPrice *Object `json:"last_price,omitempty"`
	InstrumentToken *Object `json:"instrument_token,omitempty"`
	PrevOhlc *OhlcV3 `json:"prev_ohlc,omitempty"`
	LiveOhlc *OhlcV3 `json:"live_ohlc,omitempty"`
}
