/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TokenRequest struct {
	Code *Object `json:"code"`
	// OAuth API key that is a public identifier for app
	ClientId *Object `json:"client_id"`
	// OAuth client secret that is a private secret known only to app and authorization server
	ClientSecret *Object `json:"client_secret"`
	// Authorization server will redirect the user back to the application via redirect url
	RedirectUri *Object `json:"redirect_uri"`
	// Type of grant used to get an access token
	GrantType *Object `json:"grant_type"`
}
