/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProfitAndLossMetaData struct {
	// pageNumber for pagination
	PageNumber *Object `json:"page_number,omitempty"`
	// Page size
	PageSize *Object `json:"page_size,omitempty"`
}
