/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MarginData struct {
	// Response data for instrument margin details
	Margins *Object `json:"margins,omitempty"`
	// Total margin required to execute the orders
	RequiredMargin *Object `json:"required_margin,omitempty"`
	// Total margin after margin benefit
	FinalMargin *Object `json:"final_margin,omitempty"`
}
