/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Margin struct {
	// Upfront margin mandatory by exchange for derivatives trade applicable on only FNO trade
	SpanMargin *Object `json:"span_margin,omitempty"`
	// Based on ELM percentage values provided by exchange, applicable on only FNO trade
	ExposureMargin *Object `json:"exposure_margin,omitempty"`
	// Margin applicable for any equity trade
	EquityMargin *Object `json:"equity_margin,omitempty"`
	// Option premium required.
	NetBuyPremium *Object `json:"net_buy_premium,omitempty"`
	// Application margin applicable on MCX FNO trade for certain commodities
	AdditionalMargin *Object `json:"additional_margin,omitempty"`
	// Total margin required for the basket
	TotalMargin *Object `json:"total_margin,omitempty"`
	// Tender margin
	TenderMargin *Object `json:"tender_margin,omitempty"`
}
