/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AnalyticsData struct {
	Vega *Object `json:"vega,omitempty"`
	Theta *Object `json:"theta,omitempty"`
	Gamma *Object `json:"gamma,omitempty"`
	Delta *Object `json:"delta,omitempty"`
	Iv *Object `json:"iv,omitempty"`
	Pop *Object `json:"pop,omitempty"`
}
