/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ExchangeTimingData struct {
	Exchange *Object `json:"exchange,omitempty"`
	StartTime *Object `json:"start_time,omitempty"`
	EndTime *Object `json:"end_time,omitempty"`
}
