/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetHistoricalCandleResponse struct {
	Status *Object `json:"status,omitempty"`
	// Get OHLC values for all instruments across various timeframes
	Data *HistoricalCandleData `json:"data,omitempty"`
}
