/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type HoldingsData struct {
	// The standard ISIN representing stocks listed on multiple exchanges
	Isin *Object `json:"isin,omitempty"`
	// Quantity either blocked towards open or completed order
	CncUsedQuantity *Object `json:"cnc_used_quantity,omitempty"`
	// Category of collateral assigned by RMS
	CollateralType *Object `json:"collateral_type,omitempty"`
	// Name of the company
	CompanyName *Object `json:"company_name,omitempty"`
	// This is the haircut percentage applied from RMS (applicable incase of collateral)
	Haircut *Object `json:"haircut,omitempty"`
	// Shows if the order was either Intraday, Delivery, CO or OCO
	Product *Object `json:"product,omitempty"`
	// The total holding qty
	Quantity *Object `json:"quantity,omitempty"`
	// Shows the trading symbol of the instrument
	Tradingsymbol *Object `json:"tradingsymbol,omitempty"`
	// The last traded price of the instrument
	LastPrice *Object `json:"last_price,omitempty"`
	// Closing price of the instrument from the last trading day
	ClosePrice *Object `json:"close_price,omitempty"`
	// Profit and Loss
	Pnl *Object `json:"pnl,omitempty"`
	// Day's change in absolute value for the stock
	DayChange *Object `json:"day_change,omitempty"`
	// Day's change in percentage for the stock
	DayChangePercentage *Object `json:"day_change_percentage,omitempty"`
	// Key issued by Upstox for the instrument
	InstrumentToken *Object `json:"instrument_token,omitempty"`
	// Average price at which the net holding quantity was acquired
	AveragePrice *Object `json:"average_price,omitempty"`
	// Quantity marked as collateral by RMS on users request
	CollateralQuantity *Object `json:"collateral_quantity,omitempty"`
	CollateralUpdateQuantity *Object `json:"collateral_update_quantity,omitempty"`
	// Shows the trading symbol of the instrument
	TradingSymbol *Object `json:"trading_symbol,omitempty"`
	// Quantity on T+1 day after order execution
	T1Quantity *Object `json:"t1_quantity,omitempty"`
	// Exchange of the trading symbol
	Exchange *Object `json:"exchange,omitempty"`
}
