/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProfitAndLossMetaDataWrapper struct {
	// Meta data for trade wise data details
	Page *ProfitAndLossMetaData `json:"page,omitempty"`
}
