/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PlaceOrderV3Request struct {
	// Quantity with which the order is to be placed
	Quantity *Object `json:"quantity"`
	// Signifies if the order was either Intraday, Delivery, CO or OCO
	Product *Object `json:"product"`
	// It can be one of the following - DAY(default), IOC
	Validity *Object `json:"validity"`
	// Price at which the order will be placed
	Price *Object `json:"price"`
	Tag *Object `json:"tag,omitempty"`
	Slice *Object `json:"slice,omitempty"`
	// Key of the instrument
	InstrumentToken *Object `json:"instrument_token"`
	// Type of order. It can be one of the following MARKET refers to market order LIMIT refers to Limit Order SL refers to Stop Loss Limit SL-M refers to Stop Loss Market
	OrderType *Object `json:"order_type"`
	// Indicates whether its a buy or sell order
	TransactionType *Object `json:"transaction_type"`
	// The quantity that should be disclosed in the market depth
	DisclosedQuantity *Object `json:"disclosed_quantity"`
	// If the order is a stop loss order then the trigger price to be set is mentioned here
	TriggerPrice *Object `json:"trigger_price"`
	// Signifies if the order is an After Market Order
	IsAmo *Object `json:"is_amo"`
}
