/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TradeData struct {
	// Exchange to which the order is associated
	Exchange *Object `json:"exchange,omitempty"`
	// Shows if the order was either Intraday, Delivery, CO or OCO
	Product *Object `json:"product,omitempty"`
	// Shows the trading symbol which could be a combination of symbol name, instrument, expiry date etc
	Tradingsymbol *Object `json:"tradingsymbol,omitempty"`
	// Shows the trading symbol which could be a combination of symbol name, instrument, expiry date etc
	TradingSymbol *Object `json:"trading_symbol,omitempty"`
	// Identifier issued by Upstox used for subscribing to live market quotes
	InstrumentToken *Object `json:"instrument_token,omitempty"`
	// Type of order. It can be one of the following MARKET refers to market order<br>LIMIT refers to Limit Order<br>SL refers to Stop Loss Limit<br>SL-M refers to Stop loss market
	OrderType *Object `json:"order_type,omitempty"`
	// Indicates whether the order was a buy or sell order
	TransactionType *Object `json:"transaction_type,omitempty"`
	// The total quantity traded from this particular order
	Quantity *Object `json:"quantity,omitempty"`
	// Unique order ID assigned by the exchange for the order placed
	ExchangeOrderId *Object `json:"exchange_order_id,omitempty"`
	// Unique order ID assigned internally for the order placed
	OrderId *Object `json:"order_id,omitempty"`
	// User readable time at when the trade occurred
	ExchangeTimestamp *Object `json:"exchange_timestamp,omitempty"`
	// Price at which the traded quantity is traded
	AveragePrice *Object `json:"average_price,omitempty"`
	// Trade ID generated from exchange towards traded transaction
	TradeId *Object `json:"trade_id,omitempty"`
	// The order reference ID for which the order must be modified
	OrderRefId *Object `json:"order_ref_id,omitempty"`
	// User readable timestamp at which the order was placed
	OrderTimestamp *Object `json:"order_timestamp,omitempty"`
}
