/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ExpiredFutureData struct {
	// Name of the instrument
	Name *Object `json:"name,omitempty"`
	// Segment of the instrument
	Segment *Object `json:"segment,omitempty"`
	// Exchange of the instrument
	Exchange *Object `json:"exchange,omitempty"`
	// Expiry date of the instrument
	Expiry *Object `json:"expiry,omitempty"`
	// Unique key identifying the instrument
	InstrumentKey *Object `json:"instrument_key,omitempty"`
	// Token assigned by the exchange
	ExchangeToken *Object `json:"exchange_token,omitempty"`
	// Symbol used for trading
	TradingSymbol *Object `json:"trading_symbol,omitempty"`
	// Minimum price movement
	TickSize *Object `json:"tick_size,omitempty"`
	// Number of units per lot
	LotSize *Object `json:"lot_size,omitempty"`
	// Type of the instrument
	InstrumentType *Object `json:"instrument_type,omitempty"`
	// Maximum allowed quantity
	FreezeQuantity *Object `json:"freeze_quantity,omitempty"`
	// Key of the underlying asset
	UnderlyingKey *Object `json:"underlying_key,omitempty"`
	// Type of the underlying asset
	UnderlyingType *Object `json:"underlying_type,omitempty"`
	// Symbol of the underlying asset
	UnderlyingSymbol *Object `json:"underlying_symbol,omitempty"`
	// Minimum lot size
	MinimumLot *Object `json:"minimum_lot,omitempty"`
}
