/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GttModifyOrderRequest struct {
	// Type of GTT order. It can be one of the following: SINGLE refers to a single-leg GTT order MULTIPLE refers to a multi-leg GTT order
	Type_ *Object `json:"type"`
	// Quantity with which the order is to be placed
	Quantity *Object `json:"quantity"`
	// List of rules defining the conditions for each leg in the GTT order
	Rules *Object `json:"rules"`
	// Unique identifier of the GTT order to be modified
	GttOrderId *Object `json:"gtt_order_id"`
}
