/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BrokerageTaxes struct {
	// GST charges
	Gst *Object `json:"gst,omitempty"`
	// STT charges
	Stt *Object `json:"stt,omitempty"`
	// Stamp duty charges
	StampDuty *Object `json:"stamp_duty,omitempty"`
}
