/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PositionData struct {
	// Exchange to which the order is associated
	Exchange *Object `json:"exchange,omitempty"`
	// The quantity/lot size multiplier used for calculating P&Ls
	Multiplier *Object `json:"multiplier,omitempty"`
	// Net value of the position
	Value *Object `json:"value,omitempty"`
	// Profit and loss - net returns on the position
	Pnl *Object `json:"pnl,omitempty"`
	// Shows if the order was either Intraday, Delivery, CO or OCO
	Product *Object `json:"product,omitempty"`
	// Key issued by Upstox for the instrument
	InstrumentToken *Object `json:"instrument_token,omitempty"`
	// Average price at which the net position quantity was acquired
	AveragePrice *Object `json:"average_price,omitempty"`
	// Net value of the bought quantities
	BuyValue *Object `json:"buy_value,omitempty"`
	// Quantity held previously and carried forward over night
	OvernightQuantity *Object `json:"overnight_quantity,omitempty"`
	// Amount at which the quantity is bought during the day
	DayBuyValue *Object `json:"day_buy_value,omitempty"`
	// Average price at which the day qty was bought. Default is empty string
	DayBuyPrice *Object `json:"day_buy_price,omitempty"`
	// Amount at which the quantity was bought in the previous session
	OvernightBuyAmount *Object `json:"overnight_buy_amount,omitempty"`
	// Quantity bought in the previous session
	OvernightBuyQuantity *Object `json:"overnight_buy_quantity,omitempty"`
	// Quantity bought during the day
	DayBuyQuantity *Object `json:"day_buy_quantity,omitempty"`
	// Amount at which the quantity is sold during the day
	DaySellValue *Object `json:"day_sell_value,omitempty"`
	// Average price at which the day quantity was sold
	DaySellPrice *Object `json:"day_sell_price,omitempty"`
	// Amount at which the quantity was sold in the previous session
	OvernightSellAmount *Object `json:"overnight_sell_amount,omitempty"`
	// Quantity sold short in the previous session
	OvernightSellQuantity *Object `json:"overnight_sell_quantity,omitempty"`
	// Quantity sold during the day
	DaySellQuantity *Object `json:"day_sell_quantity,omitempty"`
	// Quantity left after nullifying Day and CF buy quantity towards Day and CF sell quantity
	Quantity *Object `json:"quantity,omitempty"`
	// Last traded market price of the instrument
	LastPrice *Object `json:"last_price,omitempty"`
	// Day PnL generated against open positions
	Unrealised *Object `json:"unrealised,omitempty"`
	// Day PnL generated against closed positions
	Realised *Object `json:"realised,omitempty"`
	// Net value of the sold quantities
	SellValue *Object `json:"sell_value,omitempty"`
	// Shows the trading symbol of the instrument
	Tradingsymbol *Object `json:"tradingsymbol,omitempty"`
	// Shows the trading symbol of the instrument
	TradingSymbol *Object `json:"trading_symbol,omitempty"`
	// Closing price of the instrument from the last trading day
	ClosePrice *Object `json:"close_price,omitempty"`
	// Average price at which quantities were bought
	BuyPrice *Object `json:"buy_price,omitempty"`
	// Average price at which quantities were sold
	SellPrice *Object `json:"sell_price,omitempty"`
}
