/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OptionStrikeData struct {
	Expiry *Object `json:"expiry,omitempty"`
	Pcr *Object `json:"pcr,omitempty"`
	StrikePrice *Object `json:"strike_price,omitempty"`
	UnderlyingKey *Object `json:"underlying_key,omitempty"`
	UnderlyingSpotPrice *Object `json:"underlying_spot_price,omitempty"`
	CallOptions *PutCallOptionChainData `json:"call_options,omitempty"`
	PutOptions *PutCallOptionChainData `json:"put_options,omitempty"`
}
