/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TradeHistoryResponsePageData struct {
	PageNumber *Object `json:"page_number,omitempty"`
	PageSize *Object `json:"page_size,omitempty"`
	TotalRecords *Object `json:"total_records,omitempty"`
	TotalPages *Object `json:"total_pages,omitempty"`
}
