/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GttRule struct {
	// Defines the strategy for the GTT order leg: ENTRY - First leg order STOPLOSS - Stop-loss order TARGET - Target order
	Strategy *Object `json:"strategy"`
	// Trigger type for each leg of the order
	TriggerType *Object `json:"trigger_type"`
	// Trigger price for the GTT order leg
	TriggerPrice *Object `json:"trigger_price"`
	// Optional parameter defining the trailing gap for the GTT order
	TrailingGap *Object `json:"trailing_gap,omitempty"`
}
