/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OAuthClientExceptionCause struct {
	StackTrace *Object `json:"stackTrace,omitempty"`
	Message *Object `json:"message,omitempty"`
	LocalizedMessage *Object `json:"localizedMessage,omitempty"`
}
