/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BrokerageData struct {
	// Total charges for the order
	Total *Object `json:"total,omitempty"`
	// Brokerage charges for the order
	Brokerage *Object `json:"brokerage,omitempty"`
	// Taxes levied on order
	Taxes *BrokerageTaxes `json:"taxes,omitempty"`
	// Other charges levied
	OtherTaxes *OtherTaxes `json:"otherTaxes,omitempty"`
	// DP charges related information
	DpPlan *DpPlan `json:"dpPlan,omitempty"`
	OtherCharges *OtherTaxes `json:"other_charges,omitempty"`
	DpPlan *DpPlan `json:"dp_plan,omitempty"`
}
