/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProfitAndLossOtherChargesTaxes struct {
	// transaction charges
	Transaction *Object `json:"transaction,omitempty"`
	// clearing charges
	Clearing *Object `json:"clearing,omitempty"`
	// IPF charges
	Ipft *Object `json:"ipft,omitempty"`
	// others charges
	Others *Object `json:"others,omitempty"`
	// SEBI turnover
	SebiTurnover *Object `json:"sebi_turnover,omitempty"`
	// demat transaction charges
	DematTransaction *Object `json:"demat_transaction,omitempty"`
}
