/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MarketQuoteSymbol struct {
	Ohlc *Ohlc `json:"ohlc,omitempty"`
	Depth *DepthMap `json:"depth,omitempty"`
	// Time in milliseconds at which the feeds was updated
	Timestamp *Object `json:"timestamp,omitempty"`
	// Key issued by Upstox for the instrument
	InstrumentToken *Object `json:"instrument_token,omitempty"`
	// Shows the trading symbol of the instrument
	Symbol *Object `json:"symbol,omitempty"`
	// The last traded price of symbol
	LastPrice *Object `json:"last_price,omitempty"`
	// The volume traded today on symbol
	Volume *Object `json:"volume,omitempty"`
	// Average price
	AveragePrice *Object `json:"average_price,omitempty"`
	// Total number of outstanding contracts held by market participants exchange-wide (only F&O)
	Oi *Object `json:"oi,omitempty"`
	// The absolute change from yesterday's close to last traded price
	NetChange *Object `json:"net_change,omitempty"`
	// The total number of bid quantity available for trading
	TotalBuyQuantity *Object `json:"total_buy_quantity,omitempty"`
	// The total number of ask quantity available for trading
	TotalSellQuantity *Object `json:"total_sell_quantity,omitempty"`
	// The lower circuit of symbol
	LowerCircuitLimit *Object `json:"lower_circuit_limit,omitempty"`
	// The upper circuit of symbol
	UpperCircuitLimit *Object `json:"upper_circuit_limit,omitempty"`
	// Time in milliseconds at which last trade happened
	LastTradeTime *Object `json:"last_trade_time,omitempty"`
	OiDayHigh *Object `json:"oi_day_high,omitempty"`
	OiDayLow *Object `json:"oi_day_low,omitempty"`
}
