/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TradeWiseProfitAndLossData struct {
	// The quantity of stock traded
	Quantity *Object `json:"quantity,omitempty"`
	// ISIN of the stock
	Isin *Object `json:"isin,omitempty"`
	// Name of the scrip traded
	ScripName *Object `json:"scrip_name,omitempty"`
	// FUT - Futures   OPT - Options    EQ - Equity
	TradeType *Object `json:"trade_type,omitempty"`
	// The date on which the stock was bought
	BuyDate *Object `json:"buy_date,omitempty"`
	// The average rate at which each quantity of the stock was bought
	BuyAverage *Object `json:"buy_average,omitempty"`
	// The date on which the stock was sold
	SellDate *Object `json:"sell_date,omitempty"`
	// The average rate at which each quantity of the stock was sold
	SellAverage *Object `json:"sell_average,omitempty"`
	// Total buy amount
	BuyAmount *Object `json:"buy_amount,omitempty"`
	// Total sell amount
	SellAmount *Object `json:"sell_amount,omitempty"`
}
