/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InstrumentData struct {
	Name *Object `json:"name,omitempty"`
	Segment *Object `json:"segment,omitempty"`
	Exchange *Object `json:"exchange,omitempty"`
	Isin *Object `json:"isin,omitempty"`
	Expiry *Object `json:"expiry,omitempty"`
	Country *Object `json:"country,omitempty"`
	Latency *Object `json:"latency,omitempty"`
	Description *Object `json:"description,omitempty"`
	Currency *Object `json:"currency,omitempty"`
	Weekly *Object `json:"weekly,omitempty"`
	InstrumentKey *Object `json:"instrument_key,omitempty"`
	ExchangeToken *Object `json:"exchange_token,omitempty"`
	TradingSymbol *Object `json:"trading_symbol,omitempty"`
	ShortName *Object `json:"short_name,omitempty"`
	TickSize *Object `json:"tick_size,omitempty"`
	LotSize *Object `json:"lot_size,omitempty"`
	InstrumentType *Object `json:"instrument_type,omitempty"`
	FreezeQuantity *Object `json:"freeze_quantity,omitempty"`
	UnderlyingKey *Object `json:"underlying_key,omitempty"`
	UnderlyingType *Object `json:"underlying_type,omitempty"`
	UnderlyingSymbol *Object `json:"underlying_symbol,omitempty"`
	LastTradingDate *Object `json:"last_trading_date,omitempty"`
	StrikePrice *Object `json:"strike_price,omitempty"`
	PriceQuoteUnit *Object `json:"price_quote_unit,omitempty"`
	QtyMultiplier *Object `json:"qty_multiplier,omitempty"`
	MinimumLot *Object `json:"minimum_lot,omitempty"`
	StartTime *Object `json:"start_time,omitempty"`
	EndTime *Object `json:"end_time,omitempty"`
	WeekDays *Object `json:"week_days,omitempty"`
	GeneralDenominator *Object `json:"general_denominator,omitempty"`
	GeneralNumerator *Object `json:"general_numerator,omitempty"`
	PriceNumerator *Object `json:"price_numerator,omitempty"`
	PriceDenominator *Object `json:"price_denominator,omitempty"`
	MtfEnabled *Object `json:"mtf_enabled,omitempty"`
	MtfBracket *Object `json:"mtf_bracket,omitempty"`
	SecurityType *Object `json:"security_type,omitempty"`
}
