/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CancelOrExitOrderErrorData struct {
	// Unique code for the error state
	ErrorCode *Object `json:"errorCode,omitempty"`
	// Verbose message for the error state
	Message *Object `json:"message,omitempty"`
	// Path to property failing validation
	PropertyPath *Object `json:"propertyPath,omitempty"`
	// Invalid value for the property failing validation
	InvalidValue *Object `json:"invalidValue,omitempty"`
	ErrorCode *Object `json:"error_code,omitempty"`
	PropertyPath *Object `json:"property_path,omitempty"`
	InvalidValue *Object `json:"invalid_value,omitempty"`
	// Key of instrument
	InstrumentKey *Object `json:"instrument_key,omitempty"`
	// Reference order ID
	OrderId *Object `json:"order_id,omitempty"`
}
