/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProfitAndLossChargesData struct {
	//   Total charges for the user
	Total *Object `json:"total,omitempty"`
	// Brokerage charges for the order
	Brokerage *Object `json:"brokerage,omitempty"`
	// Taxes levied on order
	Taxes *ProfitAndLossChargesTaxes `json:"taxes,omitempty"`
	// Other charges levied
	Charges *ProfitAndLossOtherChargesTaxes `json:"charges,omitempty"`
}
