/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Instrument struct {
	// Instrument Key of the Instrument
	InstrumentKey *Object `json:"instrument_key"`
	// Quantity of the instrument to buy or sell for margin calculation
	Quantity *Object `json:"quantity"`
	// Product with which the order is to be placed
	Product *Object `json:"product"`
	// Indicates whether its a BUY or SELL order
	TransactionType *Object `json:"transaction_type"`
	// price
	Price *Object `json:"price,omitempty"`
}
