/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type WebsocketAuthRedirectResponseData struct {
	AuthorizedRedirectUri *Object `json:"authorizedRedirectUri,omitempty"`
	AuthorizedRedirectUri *Object `json:"authorized_redirect_uri,omitempty"`
}
