/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CancelOrExitMultiOrderResponse struct {
	Status *Object `json:"status,omitempty"`
	// Response data for cancel or exit order request
	Data *CancelOrExitMultiOrderData `json:"data,omitempty"`
	// Error data for cancel or exit order request
	Errors *Object `json:"errors,omitempty"`
	// Execution summary for cancel or exit order request
	Summary *BatchExecutionSummary `json:"summary,omitempty"`
}
