/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetProfileResponse struct {
	Status *Object `json:"status,omitempty"`
	// Response data for user profile
	Data *ProfileData `json:"data,omitempty"`
}
